set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_BUILD_TYPE release)

# Default to Windows 7 ABI for broader runtime compatibility.
set(_MPV_WINVER "0x0601")
if(DEFINED ENV{MPV_WIN32_WINNT} AND NOT "$ENV{MPV_WIN32_WINNT}" STREQUAL "")
    set(_MPV_WINVER "$ENV{MPV_WIN32_WINNT}")
endif()

set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} /D_WIN32_WINNT=${_MPV_WINVER} /DWINVER=${_MPV_WINVER}")
set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} /D_WIN32_WINNT=${_MPV_WINVER} /DWINVER=${_MPV_WINVER}")
